# Generated by Django 6.1 on 2026-08-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='departement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employe',
            name='matricule',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
