# Generated by Django 6.1 on 2026-08-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_employe_departement_employe_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='matricule',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
