# Generated by Django 6.1 on 2026-08-24 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_action',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('mdp', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.CreateModel(
            name='Autorised',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(db_column='action_id', on_delete=django.db.models.deletion.CASCADE, to='users.action')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 't_autorised',
                'unique_together': {('user', 'action')},
            },
        ),
    ]
