# Generated by Django 6.0.8 on 2026-08-29 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('action_libelle', models.CharField(max_length=50)),
                ('action_description', models.TextField()),
            ],
            options={
                'db_table': 't_action',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('utilisateur_id', models.AutoField(primary_key=True, serialize=False)),
                ('utilisateur_mail', models.EmailField(max_length=254, unique=True)),
                ('utilisateur_mdp', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Autoriser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoriser_action_id', models.ForeignKey(db_column='autoriser_action_id', on_delete=django.db.models.deletion.CASCADE, to='utilisateur.action')),
                ('autoriser_utilisateur_id', models.ForeignKey(db_column='autoriser_utilisateur_id', on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur')),
            ],
            options={
                'db_table': 't_autoriser',
            },
        ),
    ]
