# Generated by Django 6.0.8 on 2026-08-29 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('magasin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('magasin_nom', models.CharField(max_length=50)),
                ('localite', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
                'db_table': 't_magasin',
            },
        ),
        migrations.CreateModel(
            name='InventaireSession',
            fields=[
                ('inventaire_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_reference', models.CharField(max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé (Stock mis à jour)'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_inventaire', to='employee.service')),
                ('magasin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_inventaire', to='stock.magasin')),
            ],
            options={
                'verbose_name': "Session d'inventaire",
                'verbose_name_plural': "Sessions d'inventaire",
                'db_table': 't_inventaire_session',
            },
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('mouvement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('TRANSFERT', 'Transfert'), ('AJUSTEMENT', "Ajustement d'inventaire")], max_length=20)),
                ('origine', models.CharField(blank=True, max_length=100)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('magasin_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_entrants', to='stock.magasin')),
                ('magasin_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_sortants', to='stock.magasin')),
            ],
            options={
                'verbose_name': 'Mouvement',
                'verbose_name_plural': 'Mouvements',
                'db_table': 't_mouvement',
            },
        ),
        migrations.CreateModel(
            name='DetailMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('code_tracabilite', models.CharField(blank=True, max_length=100, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details_mouvement', to='catalogue.article')),
                ('employe_beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dotations_recues', to='employee.employer')),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stock.mouvement')),
            ],
            options={
                'verbose_name': 'Détail mouvement',
                'verbose_name_plural': 'Détails mouvement',
                'db_table': 't_detail_mouvement',
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite_physique', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ecart', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_inventaire', to='catalogue.article')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.inventairesession')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
                'db_table': 't_ligne_inventaire',
                'unique_together': {('session', 'article')},
            },
        ),
    ]
