# Generated by Django 6.0.8 on 2026-08-05 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('magasin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('localite', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
            },
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('mouvement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('TRANSFERT', 'Transfert')], max_length=20)),
                ('origine', models.CharField(blank=True, max_length=50)),
                ('motif', models.CharField(blank=True, max_length=50)),
                ('magasin_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_entrants', to='stock.magasin')),
                ('magasin_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_sortants', to='stock.magasin')),
            ],
            options={
                'verbose_name': 'Mouvement',
                'verbose_name_plural': 'Mouvements',
            },
        ),
        migrations.CreateModel(
            name='DetailMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details_mouvement', to='catalogue.article')),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stock.mouvement')),
            ],
            options={
                'verbose_name': 'Détail mouvement',
                'verbose_name_plural': 'Détails mouvement',
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('inventaire_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantite_theorique', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite_physique', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ecart', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='stock.magasin')),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='stock.mouvement')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'unique_together': {('mouvement', 'magasin', 'date')},
            },
        ),
    ]
