# Generated by Django 6.0.8 on 2026-09-10 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_remove_article_numero_de_serie_article_mode_suivi'),
        ('employee', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteArticle',
            fields=[
                ('unite_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_de_serie', models.CharField(max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('EN_STOCK', 'En stock'), ('ATTRIBUE', 'Attribué')], default='EN_STOCK', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unites', to='catalogue.article')),
                ('employe_attribue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites_attribuees', to='employee.employer')),
                ('mouvement_entree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites_creees', to='stock.detailmouvement')),
                ('mouvement_sortie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites_attribuees', to='stock.detailmouvement')),
            ],
            options={
                'verbose_name': "Unité d'article",
                'verbose_name_plural': "Unités d'articles",
                'db_table': 't_unite_article',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['article', 'statut'], name='t_unite_art_article_35a79d_idx'), models.Index(fields=['numero_de_serie'], name='t_unite_art_numero__5cc1a6_idx')],
            },
        ),
    ]
