# Generated by Django 6.1 on 2026-08-18 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventaire',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='article',
            field=models.ForeignKey(default='ART-000', on_delete=django.db.models.deletion.PROTECT, related_name='inventaires', to='catalogue.article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='ecart',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='mouvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='stock.mouvement'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('TRANSFERT', 'Transfert'), ('INVENTAIRE', 'Inventaire')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='inventaire',
            unique_together={('mouvement', 'article', 'magasin')},
        ),
    ]
