# Generated by Django 6.1 on 2026-08-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_inventaire_unique_together_inventaire_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
