# Generated by Django 6.0

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_unitearticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]