# Generated by Django 6.0.8 on 2026-09-17 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('stock', '0003_alter_mouvement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailmouvement',
            name='direction_beneficiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dotations_recues', to='employee.direction'),
        ),
    ]
