# Generated by Django 6.0.8 on 2026-09-18 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_article_is_immobilisation'),
        ('employee', '0001_initial'),
        ('stock', '0004_detailmouvement_direction_beneficiaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitearticle',
            old_name='employe_attribue',
            new_name='employe_beneficiaire',
        ),
        migrations.AddField(
            model_name='unitearticle',
            name='direction_beneficiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites_attribuees', to='employee.direction'),
        ),
        migrations.AddField(
            model_name='unitearticle',
            name='etat',
            field=models.CharField(choices=[('BON', 'Bon état'), ('MOYEN', 'État moyen'), ('MAUVAIS', 'Mauvais état'), ('HORS_USAGE', 'Hors usage'), ('PERDU', 'Perdu')], default='BON', max_length=20),
        ),
        migrations.AlterField(
            model_name='unitearticle',
            name='numero_de_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='detailmouvement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction_beneficiaire__isnull', True), ('employe_beneficiaire__isnull', True)), models.Q(('direction_beneficiaire__isnull', True), ('employe_beneficiaire__isnull', False)), models.Q(('direction_beneficiaire__isnull', False), ('employe_beneficiaire__isnull', True)), _connector='OR'), name='detail_mouv_at_most_one_beneficiary'),
        ),
    ]
