# Generated by Django 6.0.8 on 2026-09-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_rename_employe_attribue_unitearticle_employe_beneficiaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneinventaire',
            name='propositions_series',
            field=models.JSONField(blank=True, default=dict, help_text="Stockage temporaire des propositions pour les articles suivis par numéro de série. Matérialisé uniquement à la validation de la session d'inventaire.", verbose_name='Propositions de numéros de série'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('TRANSFERT', 'Transfert'), ('AJUSTEMENT', "Ajustement d'inventaire"), ('RETOUR', 'Retour au stock')], max_length=20),
        ),
    ]
