# Generated by Django 6.0.8 on 2026-09-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_ligneinventaire_propositions_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneinventaire',
            name='propositions_series',
            field=models.JSONField(blank=True, default=dict, verbose_name='Propositions de numéros de série'),
        ),
    ]
