# Generated by Django 6.0.8 on 2026-09-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_ligneinventaire_propositions_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailmouvement',
            name='prix_achat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
