# Generated by Django 6.0.8 on 2026-10-01 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_remove_article_marque_delete_articlefournisseur_and_more'),
        ('employee', '0002_employer_emp_chef_hierarchique'),
        ('stock', '0008_detailmouvement_prix_achat'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='detailmouvement',
            name='detail_mouv_at_most_one_beneficiary',
        ),
        migrations.AddField(
            model_name='detailmouvement',
            name='site_beneficiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dotations_recues', to='employee.site'),
        ),
        migrations.AddField(
            model_name='unitearticle',
            name='site_beneficiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites_attribuees', to='employee.site'),
        ),
        migrations.AddConstraint(
            model_name='detailmouvement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction_beneficiaire__isnull', True), ('employe_beneficiaire__isnull', True), ('site_beneficiaire__isnull', True)), models.Q(('direction_beneficiaire__isnull', True), ('employe_beneficiaire__isnull', False), ('site_beneficiaire__isnull', True)), models.Q(('direction_beneficiaire__isnull', False), ('employe_beneficiaire__isnull', True), ('site_beneficiaire__isnull', True)), models.Q(('direction_beneficiaire__isnull', True), ('employe_beneficiaire__isnull', True), ('site_beneficiaire__isnull', False)), _connector='OR'), name='detail_mouv_at_most_one_beneficiary'),
        ),
    ]
