# Generated by Django 6.0.8 on 2026-10-05 04:44

import django.db.models.deletion
from django.db import migrations, models


def transferer_vers_affectations(apps, schema_editor):
    Affectation = apps.get_model("stock", "Affectation")
    DetailMouvement = apps.get_model("stock", "DetailMouvement")
    UniteArticle = apps.get_model("stock", "UniteArticle")
    db_alias = schema_editor.connection.alias

    for model in (DetailMouvement, UniteArticle):
        for instance in model.objects.using(db_alias).all().iterator():
            cible = None
            for champ, type_beneficiaire in (
                ("employe_beneficiaire", "EMPLOYE"),
                ("direction_beneficiaire", "DIRECTION"),
                ("site_beneficiaire", "SITE"),
            ):
                cible_id = getattr(instance, f"{champ}_id")
                if cible_id is not None:
                    if cible is not None:
                        raise RuntimeError(
                            f"{model.__name__} #{instance.pk} possède plusieurs bénéficiaires."
                        )
                    cible = (champ.removesuffix("_beneficiaire"), cible_id, type_beneficiaire)

            if cible is None:
                if (
                    model is UniteArticle
                    and instance.statut == "ATTRIBUE"
                ):
                    raise RuntimeError(
                        f"UnitéArticle #{instance.pk} est attribuée sans bénéficiaire; "
                        "corrigez cette ligne avant la migration."
                    )
                continue

            champ_cible, cible_id, type_beneficiaire = cible
            affectation, _ = Affectation.objects.using(db_alias).get_or_create(
                **{f"{champ_cible}_id": cible_id},
                defaults={"beneficiaire_type": type_beneficiaire},
            )
            model.objects.using(db_alias).filter(pk=instance.pk).update(
                affectation_id=affectation.pk
            )


def transferer_vers_anciens_champs(apps, schema_editor):
    DetailMouvement = apps.get_model("stock", "DetailMouvement")
    UniteArticle = apps.get_model("stock", "UniteArticle")
    db_alias = schema_editor.connection.alias

    for model in (DetailMouvement, UniteArticle):
        for instance in (
            model.objects.using(db_alias)
            .exclude(affectation_id=None)
            .select_related("affectation")
            .iterator()
        ):
            affectation = instance.affectation
            champ_cible = {
                "EMPLOYE": "employe_beneficiaire",
                "DIRECTION": "direction_beneficiaire",
                "SITE": "site_beneficiaire",
            }.get(affectation.beneficiaire_type)
            if champ_cible is None:
                raise RuntimeError(
                    "Une affectation de type SALLE ne peut pas être représentée "
                    "dans l'ancien schéma."
                )
            cible_id = getattr(affectation, f"{champ_cible.removesuffix('_beneficiaire')}_id")
            model.objects.using(db_alias).filter(pk=instance.pk).update(
                **{f"{champ_cible}_id": cible_id}
            )


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employer_emp_dir_id_employer_emp_site_id'),
        ('stock', '0009_remove_detailmouvement_detail_mouv_at_most_one_beneficiary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('affectation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('beneficiaire_type', models.CharField(choices=[('EMPLOYE', 'Employé'), ('DIRECTION', 'Direction'), ('SALLE', 'Salle'), ('SITE', 'Site (agence)')], max_length=20)),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'db_table': 't_affectation',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('salle_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'db_table': 't_salle',
            },
        ),
        migrations.RemoveConstraint(
            model_name='detailmouvement',
            name='detail_mouv_at_most_one_beneficiary',
        ),
        migrations.AddField(
            model_name='affectation',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='employee.direction'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='employee.employer'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='employee.site'),
        ),
        migrations.AddField(
            model_name='detailmouvement',
            name='affectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='stock.affectation'),
        ),
        migrations.AddField(
            model_name='unitearticle',
            name='affectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites_attribuees', to='stock.affectation'),
        ),
        migrations.AddField(
            model_name='salle',
            name='localite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salles', to='employee.site'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='stock.salle'),
        ),
        migrations.RunPython(
            transferer_vers_affectations,
            transferer_vers_anciens_champs,
        ),
        migrations.RemoveField(
            model_name='unitearticle',
            name='direction_beneficiaire',
        ),
        migrations.RemoveField(
            model_name='unitearticle',
            name='employe_beneficiaire',
        ),
        migrations.RemoveField(
            model_name='unitearticle',
            name='site_beneficiaire',
        ),
        migrations.RemoveField(
            model_name='detailmouvement',
            name='direction_beneficiaire',
        ),
        migrations.RemoveField(
            model_name='detailmouvement',
            name='employe_beneficiaire',
        ),
        migrations.RemoveField(
            model_name='detailmouvement',
            name='site_beneficiaire',
        ),
        migrations.AddConstraint(
            model_name='salle',
            constraint=models.UniqueConstraint(fields=('nom', 'localite'), name='salle_unique'),
        ),
        migrations.AddConstraint(
            model_name='affectation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('beneficiaire_type', 'EMPLOYE'), ('direction__isnull', True), ('employe__isnull', False), ('salle__isnull', True), ('site__isnull', True)), models.Q(('beneficiaire_type', 'DIRECTION'), ('direction__isnull', False), ('employe__isnull', True), ('salle__isnull', True), ('site__isnull', True)), models.Q(('beneficiaire_type', 'SALLE'), ('direction__isnull', True), ('employe__isnull', True), ('salle__isnull', False), ('site__isnull', True)), models.Q(('beneficiaire_type', 'SITE'), ('direction__isnull', True), ('employe__isnull', True), ('salle__isnull', True), ('site__isnull', False)), _connector='OR'), name='affectation_type_coherent_avec_cible'),
        ),
        migrations.AddConstraint(
            model_name='affectation',
            constraint=models.UniqueConstraint(condition=models.Q(('employe__isnull', False)), fields=('employe',), name='affectation_unique_employe'),
        ),
        migrations.AddConstraint(
            model_name='affectation',
            constraint=models.UniqueConstraint(condition=models.Q(('direction__isnull', False)), fields=('direction',), name='affectation_unique_direction'),
        ),
        migrations.AddConstraint(
            model_name='affectation',
            constraint=models.UniqueConstraint(condition=models.Q(('salle__isnull', False)), fields=('salle',), name='affectation_unique_salle'),
        ),
        migrations.AddConstraint(
            model_name='affectation',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', False)), fields=('site',), name='affectation_unique_site'),
        ),
    ]
