# Generated by Django 6.0.8 on 2026-10-05 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employer_emp_dir_id_employer_emp_site_id'),
        ('stock', '0010_affectation_salle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventairesession',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_inventaire', to='stock.salle'),
        ),
        migrations.AddField(
            model_name='inventairesession',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_inventaire', to='employee.site'),
        ),
    ]
