# Generated by Django 6.0.8 on 2026-08-29 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('dir_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dir_libelle', models.CharField(max_length=50)),
                ('dir_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_direction',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serv_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('serv_libelle', models.CharField(max_length=50)),
                ('serv_info', models.TextField()),
                ('serv_dir_id', models.ForeignKey(db_column='serv_dir_id', on_delete=django.db.models.deletion.CASCADE, to='employee.direction')),
            ],
            options={
                'db_table': 't_service',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('emp_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('emp_nom', models.CharField(max_length=255)),
                ('emp_matricule', models.CharField(max_length=15)),
                ('emp_contact', models.CharField(max_length=50)),
                ('emp_fonction', models.CharField(max_length=50)),
                ('emp_utilisateur_id', models.ForeignKey(blank=True, db_column='emp_utilisateur_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur')),
                ('emp_serv_id', models.ForeignKey(db_column='emp_serv_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.service')),
            ],
            options={
                'db_table': 't_employee',
            },
        ),
    ]
