# Generated by Django 6.0.8 on 2026-10-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employer_emp_dir_id_employer_emp_site_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='site',
        ),
    ]
