# Generated by Django 6.0.8 on 2026-08-29 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('commande_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('objet', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_agent', models.CharField(blank=True, max_length=255)),
                ('employe_demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_demandees', to='employee.employer')),
                ('employe_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_traitees', to='employee.employer')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 't_commande',
            },
        ),
        migrations.CreateModel(
            name='DetailCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details_commande', to='catalogue.article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='commande.commande')),
            ],
            options={
                'verbose_name': 'Détail commande',
                'verbose_name_plural': 'Détails commande',
                'db_table': 't_detail_commande',
            },
        ),
        migrations.CreateModel(
            name='AttributionDetailCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('code_unique', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('employe_beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributions_articles', to='employee.employer')),
                ('detail_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='commande.detailcommande')),
            ],
            options={
                'db_table': 't_attribution_detail_commande',
            },
        ),
    ]
