# Generated by Django 6.0.8 on 2026-09-17 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributiondetailcommande',
            name='direction_beneficiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributions_articles', to='employee.direction'),
        ),
        migrations.AlterField(
            model_name='attributiondetailcommande',
            name='employe_beneficiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributions_articles', to='employee.employer'),
        ),
    ]
