# Generated by Django 6.0.8 on 2026-09-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_attributiondetailcommande_direction_beneficiaire_and_more'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attributiondetailcommande',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction_beneficiaire__isnull', True), ('employe_beneficiaire__isnull', False)), models.Q(('direction_beneficiaire__isnull', False), ('employe_beneficiaire__isnull', True)), _connector='OR'), name='attrib_exactly_one_beneficiary'),
        ),
    ]
