# Generated by Django 6.0.8 on 2026-09-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_attributiondetailcommande_attrib_exactly_one_beneficiary'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributiondetailcommande',
            name='motif_refus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motif de refus'),
        ),
        migrations.AddField(
            model_name='attributiondetailcommande',
            name='quantite_demandee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité demandée'),
        ),
        migrations.AddField(
            model_name='attributiondetailcommande',
            name='quantite_validee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantité validée'),
        ),
        migrations.AddField(
            model_name='attributiondetailcommande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='attributiondetailcommande',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('statut', 'VALIDEE'), _negated=True), models.Q(('quantite_validee__isnull', False), ('quantite_validee__gt', 0)), _connector='OR'), name='attrib_validee_quantite_obligatoire'),
        ),
    ]
