# Generated by Django 6.0.8 on 2026-10-01 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_attributiondetailcommande_motif_refus_and_more'),
        ('employee', '0002_employer_emp_chef_hierarchique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attributiondetailcommande',
            name='attrib_exactly_one_beneficiary',
        ),
        migrations.AddField(
            model_name='attributiondetailcommande',
            name='site_beneficiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributions_articles', to='employee.site'),
        ),
        migrations.AddConstraint(
            model_name='attributiondetailcommande',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction_beneficiaire__isnull', True), ('employe_beneficiaire__isnull', True), ('site_beneficiaire__isnull', True)), models.Q(('direction_beneficiaire__isnull', True), ('employe_beneficiaire__isnull', False), ('site_beneficiaire__isnull', True)), models.Q(('direction_beneficiaire__isnull', False), ('employe_beneficiaire__isnull', True), ('site_beneficiaire__isnull', True)), models.Q(('direction_beneficiaire__isnull', True), ('employe_beneficiaire__isnull', True), ('site_beneficiaire__isnull', False)), _connector='OR'), name='attrib_exactly_one_beneficiary'),
        ),
    ]
