# Generated by Django 6.0.8 on 2026-10-05 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0005_remove_attributiondetailcommande_attrib_exactly_one_beneficiary_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attributiondetailcommande',
            name='attrib_exactly_one_beneficiary',
        ),
    ]
