# Generated by Django 6.0.8 on 2026-10-05 04:44

import django.db.models.deletion
from django.db import migrations, models


def transferer_vers_affectation(apps, schema_editor):
    Affectation = apps.get_model("stock", "Affectation")
    Attribution = apps.get_model("commande", "AttributionDetailCommande")
    db_alias = schema_editor.connection.alias

    for attribution in Attribution.objects.using(db_alias).all().iterator():
        cibles = [
            (champ, getattr(attribution, f"{champ}_id"), type_beneficiaire)
            for champ, type_beneficiaire in (
                ("employe_beneficiaire", "EMPLOYE"),
                ("direction_beneficiaire", "DIRECTION"),
                ("site_beneficiaire", "SITE"),
            )
            if getattr(attribution, f"{champ}_id") is not None
        ]
        if len(cibles) != 1:
            raise RuntimeError(
                f"AttributionDetailCommande #{attribution.pk} ne possède pas "
                "exactement un bénéficiaire; corrigez cette ligne avant la migration."
            )

        champ_cible, cible_id, type_beneficiaire = cibles[0]
        champ_cible = champ_cible.removesuffix("_beneficiaire")
        affectation, _ = Affectation.objects.using(db_alias).get_or_create(
            **{f"{champ_cible}_id": cible_id},
            defaults={"beneficiaire_type": type_beneficiaire},
        )
        Attribution.objects.using(db_alias).filter(pk=attribution.pk).update(
            affectation_id=affectation.pk
        )


def transferer_vers_anciens_champs(apps, schema_editor):
    Attribution = apps.get_model("commande", "AttributionDetailCommande")
    db_alias = schema_editor.connection.alias

    for attribution in (
        Attribution.objects.using(db_alias)
        .exclude(affectation_id=None)
        .select_related("affectation")
        .iterator()
    ):
        affectation = attribution.affectation
        champ_cible = {
            "EMPLOYE": "employe_beneficiaire",
            "DIRECTION": "direction_beneficiaire",
            "SITE": "site_beneficiaire",
        }.get(affectation.beneficiaire_type)
        if champ_cible is None:
            raise RuntimeError(
                "Une affectation de type SALLE ne peut pas être représentée "
                "dans l'ancien schéma des attributions."
            )
        cible_id = getattr(affectation, f"{champ_cible.removesuffix('_beneficiaire')}_id")
        Attribution.objects.using(db_alias).filter(pk=attribution.pk).update(
            **{f"{champ_cible}_id": cible_id}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0006_remove_attributiondetailcommande_attrib_exactly_one_beneficiary'),
        ('stock', '0010_affectation_salle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributiondetailcommande',
            name='affectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributions_articles', to='stock.affectation'),
        ),
        migrations.RunPython(
            transferer_vers_affectation,
            transferer_vers_anciens_champs,
        ),
        migrations.RemoveField(
            model_name='attributiondetailcommande',
            name='direction_beneficiaire',
        ),
        migrations.RemoveField(
            model_name='attributiondetailcommande',
            name='employe_beneficiaire',
        ),
        migrations.RemoveField(
            model_name='attributiondetailcommande',
            name='site_beneficiaire',
        ),
    ]
