# Generated by Django 6.0.8 on 2026-08-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('commande_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_comande', models.DateTimeField(auto_now_add=True)),
                ('objet', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_agent', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='DetailCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Détail commande',
                'verbose_name_plural': 'Détails commande',
            },
        ),
    ]
