# Generated by Django 6.0.8 on 2026-08-05 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0001_initial'),
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='utilisateur_demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_demandees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='utilisateur_traitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detailcommande',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details_commande', to='catalogue.article'),
        ),
        migrations.AddField(
            model_name='detailcommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='achats.commande'),
        ),
    ]
