# Generated by Django 6.0.8 on 2026-08-05 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('categorie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('fournisseur_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=50)),
                ('contact', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('code_article', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('code_barre', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('designation', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('marque', models.CharField(blank=True, max_length=30)),
                ('modele', models.CharField(blank=True, max_length=30)),
                ('unite', models.CharField(blank=True, max_length=20)),
                ('mode_suivi', models.CharField(choices=[('QUANTITE', 'Quantité simple'), ('LOT', 'Suivi par lot'), ('NUMERO_SERIE', 'Suivi par numéro de série')], default='QUANTITE', max_length=20)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='catalogue.categorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='ArticleFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs_liaison', to='catalogue.article')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_liaison', to='catalogue.fournisseur')),
            ],
            options={
                'verbose_name': 'Article fournisseur',
                'verbose_name_plural': 'Articles fournisseurs',
                'unique_together': {('article', 'fournisseur')},
            },
        ),
    ]
