# Generated by Django 6.1 on 2026-08-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='seuil',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
