# Generated by Django 6.0.8 on 2026-09-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='numero_de_serie',
        ),
        migrations.AddField(
            model_name='article',
            name='mode_suivi',
            field=models.CharField(choices=[('QUANTITE', 'Quantité simple'), ('LOT', 'Suivi par lot'), ('NUMERO_SERIE', 'Suivi par numéro de série')], default='QUANTITE', max_length=20),
        ),
    ]
