# Generated by Django 6.0.8 on 2026-09-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_remove_article_numero_de_serie_article_mode_suivi'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_immobilisation',
            field=models.BooleanField(default=True),
        ),
    ]
