# Generated by Django 6.0.8 on 2026-09-23 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_article_is_immobilisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='marque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='catalogue.marque'),
        ),
        migrations.AlterField(
            model_name='article',
            name='mode_suivi',
            field=models.CharField(choices=[('QUANTITE', 'Quantité simple'), ('NUMERO_SERIE', 'Suivi par numéro de série')], default='QUANTITE', max_length=20),
        ),
    ]
