# Generated by Django 6.0.8 on 2026-09-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_article_marque_alter_article_mode_suivi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='marque',
        ),
        migrations.DeleteModel(
            name='ArticleFournisseur',
        ),
        migrations.DeleteModel(
            name='Marque',
        ),
    ]
